version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: liner-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-liner}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-linerpass}
      POSTGRES_DB: ${POSTGRES_DB:-linerdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile   # lascialo così solo se il tuo file si chiama davvero "dockerfile"
    image: liner-backend:latest
    container_name: liner-backend
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-liner}:${POSTGRES_PASSWORD:-linerpass}@db:5432/${POSTGRES_DB:-linerdb}
      CORS_ORIGINS: "*"   # poi la stringiamo
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      
    image: liner-frontend:latest
    container_name: liner-frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-net

  caddy:
    image: caddy:2-alpine
    container_name: liner-proxy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge