name: Feature request
description: Proponi una nuova funzionalità o miglioramento
title: "[FEAT] "
labels: ["type:feature", "status:ready"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Obiettivo
      description: Quale problema risolve? Qual è il valore per utente/business?
    validations: { required: true }
  - type: textarea
    id: scope
    attributes:
      label: Ambito
      description: Cosa è IN/OUT? (brief)
      placeholder: "IN: ...\nOUT: ..."
  - type: textarea
    id: details
    attributes:
      label: Dettagli (UX/API)
      description: Schizzi, API, esempi di payload, criteri di UX
  - type: textarea
    id: acceptance
    attributes:
      label: Criteri di accettazione
      description: Come verifichiamo che è completa?
      placeholder: "- [ ] ...\n- [ ] ..."
    validations: { required: true }
  - type: textarea
    id: deps
    attributes:
      label: Dipendenze/Impatto
      description: Servizi, migrazioni, sicurezza, performance
